---
# tasks file for roles/db

- name: Installation de MariaDB
  ansible.builtin.apt:
    name: mariadb-server
    update_cache: yes
    cache_valid_time: 3600

- name: Configuration MariaDB - Écouter sur l'interface de Backend DB
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address.*'
    line: 'bind-address = {{ bind_address }}'
  register: reload_mariadb

- name: Rechargement de MariaDB
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
  when: reload_mariadb.changed
