---
- name: Installation de MariaDB
  ansible.builtin.apt:
    name:
    - mariadb-server
    - python3-mysqldb
    update_cache: yes
    cache_valid_time: 3600

- name: Configuration MariaDB - Écouter sur l'interface de Backend DB
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = {{ bind_address }}'
  register: restart_mariadb

- name: Création des bases MariaDB
  community.mysql.mysql_db:
    name: "{{ item }}"
    state: present
  loop: "{{ groups['www_servers'] }}"
  when: hostvars[item].www_type == 'wordpress'

- name: Création des utilisateurs MariaDB
  community.mysql.mysql_user:
    name: "{{ hostvars[item].wordpress_db_user }}"
    password: "{{ hostvars[item].wordpress_db_password }}"
    host: "{{ hostvars[item].be_address_db }}"
    priv: "{{ item }}.*:ALL,GRANT"
  loop: "{{ groups['www_servers'] }}"
  when: hostvars[item].www_type == 'wordpress'

- name: Redémarrage de MariaDB
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
  when: restart_mariadb.changed
