plugin: openstack.cloud.openstack
expand_hostvars: yes
fail_on_errors: yes
cache: yes
cache_plugin: ansible.builtin.jsonfile
cache_connection: /tmp/openstack_inventory
cache_prefix: openstack
cache_timeout: 300
clouds_yaml_path: [clouds.yaml]
compose:
  ansible_host: openstack.accessIPv4 if openstack.metadata.ssh_access == "fe" else openstack['addresses']['private-net-FE'][0]['addr']
  ansible_ssh_host: openstack.accessIPv4 if openstack.metadata.ssh_access == "fe" else openstack['addresses']['private-net-FE'][0]['addr']
