---
# tasks file for roles/www

- name: Installation de Apache2
  ansible.builtin.apt:
    name: apache2
    update_cache: yes
    cache_valid_time: 3600

- name: Création page Web
  ansible.builtin.template:
    src: var_www_html_index.html
    dest: /var/www/html/index.html
  #with_list: "{{ groups['www'] }}"
  #with_items: [ "{{ groups['www'] }}" ]
