---
- name: Installation des paquets
  ansible.builtin.apt:
    name: "{{ packages[www_type] | default([]) }}"
    update_cache: yes
    cache_valid_time: 3600

- include_tasks: "{{ www_type }}.yml"

- name: Apache2 - Activation des modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache2_modules_to_enable[www_type] | default([]) }}"
  notify: Redémarrage de Apache2

- name: Apache2 - Activation des confs
  ansible.builtin.file:
    src: "/etc/apache2/conf-available/{{ item }}.conf"
    dest: "/etc/apache2/conf-enabled/{{ item }}.conf"
    state: link
  loop: "{{ apache2_confs_to_enable[www_type] | default([]) }}"
  notify: Rechargement de Apache2
