---
# Paquets à installer
packages:
  bootstrap:
  - apache2
  wordpress:
  - apache2
  - php-fpm
  - php-json
  - php-mysql
  - php-curl
  - php-dompdf
  - php-imagick
  - php-mbstring
  - php-xml
  - php-zip
  - php-gd
  - php-intl

# Modules Apache2 à activer
apache2_modules_to_enable:
  bootstrap: []
  wordpress:
  - proxy_fcgi
  - setenvif

# Conf Apache2 à activer
apache2_confs_to_enable:
  bootstrap: []
  wordpress:
  - php7.4-fpm

# URL de l'archive Wordpress à utiliser
wordpress_tar_url: https://wordpress.org/latest.tar.gz


